# render.yaml — simplified version focusing on API first

services:
  - name: sentinelmesh-api
    type: web
    env: python
    repo: https://github.com/rishit03/SentinelMesh # Ensure this is your correct repo URL
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SENTINELMESH_TOKEN
        value: rishit-org-token  # Your API token
      - key: DATABASE_URL
        value: sqlite:///./sentinelmesh.db
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health

  - name: sentinelmesh-dashboard # Keep this service for the Streamlit dashboard
    type: web
    env: docker
    repo: https://github.com/rishit03/SentinelMesh
    region: oregon
    plan: free
    branch: main
    rootDir: dashboard
    envVars:
      - key: SENTINELMESH_USER
        value: rishit03
      - key: SENTINELMESH_PASS
        value: 12345678
      - key: API_BASE
        value: https://sentinelmesh-api.onrender.com

