# render.yaml — monorepo with two Docker services

services:
  - name: sentinelmesh-api
    type: web
    env: docker
    repo: https://github.com/rishit03/SentinelMesh
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    envVars:
      - key: SENTINELMESH_USER
        value: rihsit03
      - key: SENTINELMESH_PASS
        value: 12345678

  - name: sentinelmesh-dashboard
    type: web
    env: docker
    repo: https://github.com/rishit03/SentinelMesh
    region: oregon
    plan: free
    branch: main
    rootDir: dashboard
    envVars:
      - key: SENTINELMESH_USER
        value: rishit
      - key: SENTINELMESH_PASS
        value: 12345678
      - key: API_BASE
        value: https://sentinelmesh-api.onrender.com  # 🔁 Update this after API deploys
