# render.yaml — monorepo with backend API and dashboard services

services:
  - name: sentinelmesh-api
    type: web
    env: python
    repo: https://github.com/rishit03/SentinelMesh
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Navigate to the frontend directory (relative to repo root) and build the React app
      cd ../frontend/sentinelmesh-dashboard && npm install --legacy-peer-deps && npm run build
      # Copy the built React app to the backend directory for serving
      cp -r dist ../../backend/static_frontend
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SENTINELMESH_TOKEN
        value: rishit-org-token  # Your API token

  - name: sentinelmesh-dashboard
    type: web
    env: docker
    repo: https://github.com/rishit03/SentinelMesh
    region: oregon
    plan: free
    branch: main
    rootDir: dashboard
    envVars:
      - key: SENTINELMESH_USER
        value: rishit03
      - key: SENTINELMESH_PASS
        value: 12345678
      - key: API_BASE
        value: https://sentinelmesh-api.onrender.com