name: 🐞 Bug Report
description: Report something that isn't working
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue you encountered.
      placeholder: Tell us what you saw.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we replicate the bug?
      placeholder: 1. Run sentinelmesh-cli\n2. Observe error...
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: Operating system / Python version
      placeholder: e.g., macOS 14, Python 3.10
